<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
</head>

<body>
    <h1 class="text-center">The Friends School</h1>
    <h3 class="text-center ">Result Sheet</h3>
    <div id="showtable">
    <?php
    if (isset($_GET['class'])) {
        $class           = $_GET["class"];
        $roll            = $_GET["roll"];

        // Subject Table
        $sql3 = "SELECT * FROM subject";
        $query3 = $conn->query($sql3);
        $data_list1 = array();
        while ($data = mysqli_fetch_assoc($query3)) {
            $subject_id    = $data['subject_id'];
            $subject_name  = $data['subject_name'];

            $data_list1[$subject_id] = $subject_name;
        }
        // Class Table
        $sql1 = "SELECT* FROM class";
        $query1 = $conn->query($sql1);
        $data_list2 = array();
        while ($data = mysqli_fetch_assoc($query1)) {
            $class_id = $data['class_id'];
            $class_name = $data['class_name'];

            $data_list2[$class_id] = $class_name;
        }
        // Admission Table
        $sql2 = "SELECT* FROM admission WHERE class=$class AND student_roll=$roll ";
        $query2 = $conn->query($sql2);
        while ($data = mysqli_fetch_assoc($query2)) {
            $student_name = $data['student_name'];
        }
        echo "<h4>Name: $student_name</h4>";
        // Result Table
        echo "<table class='table table-striped'>
                    <tr>
                        <th>Subject</th>
                        <th>Midterm</th>
                        <th>Final</th>
                        <th>Total</th>
                    </tr>";
        $sql5 = "SELECT * FROM result WHERE class=$class AND  student_roll=$roll";
        $query5 = $conn->query($sql5);
        $data2 = mysqli_fetch_assoc($query5);
        $class_name     = $data2['class'];
        $student_roll   = $data2['student_roll'];
        echo "<h4>Class: $data_list2[$class_name]</h4>";
        echo "<h4>Roll: $student_roll</h4> <br>";
        $sql = "SELECT * FROM result WHERE class=$class AND  student_roll=$roll";
        $query = $conn->query($sql);
        while ($data = mysqli_fetch_array($query)) {
            $subject        = $data['subject'];
            $midterm        = $data['midterm'];
            $final          = $data['final'];
            $total = $midterm + $final;
            echo "<tr>
                            <td>$data_list1[$subject]</td>    
                            <td>$midterm</td>
                            <td>$final</td>
                            <td>$total</td>
                        </tr>";
        }
        echo "</table>";
    }
    ?>
    </div>
    <p class="text-center">**The Result is generated by online. No signature will be needed.**</p><br><br>
    <div class="float-right">
        <hr>
        <span class="text-start ">Md Nasim Khan</span><br>
        <span class="text-start">Principal</span><br>
        <span class="text-start">The Friends School</span><br>
        <span class="text-start">DSC,Ashulia,Uganda</span><br>
    </div>

</body>

</html>